const API=String(window.OMNIBOT_API||'').trim().replace(/\/$/,'');
const params=new URLSearchParams(location.search), readOnly=location.pathname.endsWith('embed.html');
const state={guilds:[],guildId:params.get('guild'),channels:[],channelId:params.get('channel'),messages:[],ws:null,reconnect:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const initials=v=>String(v||'?').trim().slice(0,2).toUpperCase();
const configured=()=>API&&/^https?:\/\//.test(API)&&!API.includes('YOUR_CLOUDFLARE');
async function api(path,options){if(!configured())throw Error('OmniBot is not configured. Set OMNIBOT_API in config.js.');const r=await fetch(API+path,options);const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.error||`Request failed (${r.status})`);return d;}
function setStatus(t){const e=$('connection-status');if(e)e.textContent=t;}
function renderGuilds(){const e=$('guilds');if(!e)return;e.innerHTML=state.guilds.map(g=>`<button class="guild ${g.id===state.guildId?'active':''}" data-id="${g.id}" title="${esc(g.name)}">${g.icon?`<img src="${g.icon}" alt="">`:initials(g.name)}</button>`).join('');e.querySelectorAll('.guild').forEach(b=>b.onclick=()=>selectGuild(b.dataset.id));}
function renderChannels(){const e=$('channels');if(!e)return;const cats=new Map(state.channels.filter(c=>c.type===4).map(c=>[c.id,c]));const byParent=new Map();for(const c of state.channels.filter(c=>c.type===0)){const key=c.parentId||'__root__';if(!byParent.has(key))byParent.set(key,[]);byParent.get(key).push(c);}let html='';for(const [parent,list] of byParent){if(parent!=='__root__')html+=`<div class="channel-category">${esc(cats.get(parent)?.name||'Channels')}</div>`;for(const c of list)html+=`<button class="channel ${c.id===state.channelId?'active':''}" data-id="${c.id}"><span class="hash">#</span>${esc(c.name)}</button>`;}e.innerHTML=html||'<div class="empty">No text channels available.</div>';e.querySelectorAll('.channel').forEach(b=>b.onclick=()=>selectChannel(b.dataset.id));}
function renderMessages(scroll=true){const e=$('messages');if(!e)return;if(!state.messages.length){e.innerHTML='<div class="empty">No messages yet.</div>';return;}e.innerHTML=state.messages.map(m=>{const n=m.author?.globalName||m.author?.username||'Unknown';const attachments=(m.attachments||[]).map(a=>a.contentType?.startsWith('image/')?`<img class="attachment" loading="lazy" src="${a.url}" alt="${esc(a.name)}">`:`<a class="attachment file" target="_blank" rel="noopener" href="${a.url}">📎 ${esc(a.name)}</a>`).join('');return `<article class="message" data-id="${m.id}"><div>${m.author?.avatar?`<img class="avatar" src="${m.author.avatar}" alt="">`:`<div class="avatar">${initials(n)}</div>`}</div><div><div class="message-top"><span class="author">${esc(n)}</span><time class="timestamp">${new Date(m.createdAt).toLocaleString()}</time></div><div class="content">${esc(m.content)}</div>${attachments}${m.editedAt?'<span class="edited">edited</span>':''}</div></article>`}).join('');if(scroll)e.scrollTop=e.scrollHeight;}
async function loadStructure(id){const data=await api(`/api/guilds/${encodeURIComponent(id)}/structure`);state.guildId=id;state.channels=data.channels||[];if($('guild-name'))$('guild-name').textContent=data.guild?.name||'OmniBot';renderChannels();const first=state.channels.find(c=>c.type===0);const wanted=state.channelId&&state.channels.find(c=>c.id===state.channelId&&c.type===0);if(wanted)await selectChannel(wanted.id);else if(first)await selectChannel(first.id);}
async function selectGuild(id){state.channelId=null;renderGuilds();await loadStructure(id);}
async function selectChannel(id){state.channelId=id;const c=state.channels.find(x=>x.id===id);if($('channel-name'))$('channel-name').textContent=c?.name||'channel';if($('message-input')){$('message-input').disabled=readOnly;$('message-input').placeholder=readOnly?'Read-only server embed':`Message #${c?.name||'channel'}`;}if($('send-button'))$('send-button').disabled=readOnly;renderChannels();state.messages=await api(`/api/channels/${encodeURIComponent(id)}/messages`);renderMessages();subscribe();if(!readOnly)history.replaceState(null,'',`?guild=${encodeURIComponent(state.guildId||'')}&channel=${encodeURIComponent(id)}`);}
function wsUrl(){return API.replace(/^http/,'ws')+'/ws';}
function connect(){if(!configured())return;clearTimeout(state.reconnect);state.ws?.close();state.ws=new WebSocket(wsUrl());state.ws.onopen=()=>{setStatus('Connected');subscribe();};state.ws.onclose=()=>{setStatus('Reconnecting…');state.reconnect=setTimeout(connect,2000);};state.ws.onerror=()=>setStatus('Connection error');state.ws.onmessage=e=>{let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='status'){setStatus(m.gatewayConnected?'Live':'Bot starting…');return;}if(m.type==='guilds'){state.guilds=m.data||[];renderGuilds();return;}if(m.data?.channelId!==state.channelId)return;if(m.type==='message:create'&&!state.messages.some(x=>x.id===m.data.id)){state.messages.push(m.data);renderMessages(true);}else if(m.type==='message:update'){const i=state.messages.findIndex(x=>x.id===m.data.id);if(i>=0){state.messages[i]={...state.messages[i],...m.data};renderMessages(false);}}else if(m.type==='message:delete'){state.messages=state.messages.filter(x=>x.id!==m.data.id);renderMessages(false);}};}
function subscribe(){if(state.ws?.readyState===1&&state.channelId)state.ws.send(JSON.stringify({type:'subscribe',guildId:state.guildId,channelId:state.channelId}));}
$('composer')?.addEventListener('submit',async e=>{e.preventDefault();if(readOnly)return;const input=$('message-input'),button=$('send-button'),content=input.value.trim();if(!content||!state.channelId)return;button.disabled=true;try{await api(`/api/channels/${encodeURIComponent(state.channelId)}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content})});input.value='';}catch(err){alert(err.message);}finally{button.disabled=false;}});
(async()=>{try{if(!configured())throw Error('OmniBot is not configured. Set OMNIBOT_API in config.js.');connect();if(readOnly&&state.guildId){await loadStructure(state.guildId);return;}for(let i=0;i<10&&!state.guilds.length;i++){state.guilds=await api('/api/guilds');if(!state.guilds.length)await new Promise(r=>setTimeout(r,1500));}renderGuilds();if(state.guildId&&state.guilds.some(g=>g.id===state.guildId))await selectGuild(state.guildId);else if(state.guilds[0])await selectGuild(state.guilds[0].id);else $('messages').innerHTML='<div class="empty">OmniBot has not received any servers yet. Open the Worker health endpoint and check <b>tokenConfigured</b> and <b>lastGatewayError</b>.</div>';}catch(err){$('messages').innerHTML=`<div class="empty">${esc(err.message)}</div>`;}})();
